# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Trnaslate.create(english_letter: 'A', arabic_letter: 'أ')
Trnaslate.create(english_letter: 'A', arabic_letter: 'ا')
Trnaslate.create(english_letter: 'B', arabic_letter: 'ب')
Trnaslate.create(english_letter: 'C', arabic_letter: '/')
Trnaslate.create(english_letter: 'D', arabic_letter: 'د')
Trnaslate.create(english_letter: 'E', arabic_letter: 'ع')
Trnaslate.create(english_letter: 'F', arabic_letter: '.')
Trnaslate.create(english_letter: 'G', arabic_letter: 'ق')
Trnaslate.create(english_letter: 'H', arabic_letter: 'ه')
Trnaslate.create(english_letter: 'H', arabic_letter: 'هـ')
Trnaslate.create(english_letter: 'I', arabic_letter: '/')
Trnaslate.create(english_letter: 'j', arabic_letter: 'ح')
Trnaslate.create(english_letter: 'K', arabic_letter: 'ك')
Trnaslate.create(english_letter: 'L', arabic_letter: 'ل')
Trnaslate.create(english_letter: 'M', arabic_letter: '/')
Trnaslate.create(english_letter: 'N', arabic_letter: 'ن')
Trnaslate.create(english_letter: 'O', arabic_letter: '/')
Trnaslate.create(english_letter: 'P', arabic_letter: '/')
Trnaslate.create(english_letter: 'Q', arabic_letter: '/')
Trnaslate.create(english_letter: 'R', arabic_letter: 'ر')
Trnaslate.create(english_letter: 'S', arabic_letter: 'س')
Trnaslate.create(english_letter: 'T', arabic_letter: 'ط')
Trnaslate.create(english_letter: 'U', arabic_letter: 'و')
Trnaslate.create(english_letter: 'V', arabic_letter: '/')
Trnaslate.create(english_letter: 'W', arabic_letter: '/')
Trnaslate.create(english_letter: 'X', arabic_letter: 'ص')
Trnaslate.create(english_letter: 'Y', arabic_letter: 'م')
Trnaslate.create(english_letter: 'Z', arabic_letter: 'م')
